use std::fs::{self, File};
use std::path::Path;
use anyhow::Result;
use std::io::{Write, BufRead, BufReader};


pub fn generate_loader(features: &[String]) -> Result<()> {
    let loader_path = Path::new("src/feature_loader.rs");
    let mut loader_file = File::create(loader_path)?;

    writeln!(loader_file, "// AUTO-GENERATED BY XBUILD")?;
    writeln!(loader_file, "pub fn init_features() {{")?;

    for feat in features{
        writeln!(loader_file, "    #[cfg(feature = \"{0}\")]", feat)?;
        writeln!(loader_file, "    {{ crate::features::{0}::init(); }}", feat)?;
    }

    writeln!(loader_file, "}}")?;
    println!("[+] Regenerated feature_loader.rs with {} feature(s)", features.len());
    Ok(())
}