use std::collections::HashMap;
use std::fs::{self, File};
use std::io::{BufRead, BufReader, Write};
use std::path::Path;

use anyhow::{Context, Result};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct FeatureEntry {
    pub path: String,
    pub call: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct FeaturesMap(pub HashMap<String, FeatureEntry>);

pub fn read_feature_map(path: &Path) -> Result<FeaturesMap> {
    let file = File::open(path).context("Failed to open feature_map.yml")?;
    let map: HashMap<String, FeatureEntry> =
        serde_yaml::from_reader(file).context("Invalid YML in feature_map.yml")?;
    Ok(FeaturesMap(map))
}

pub fn generate_loader(map: &FeaturesMap) -> Result<()> {
    let loader_path = Path::new("src/feature_loader.rs");
    let mut loader_file = File::create(loader_path)?;

    writeln!(loader_file, "// AUTO-GENERATED BY KEIROS")?;
    writeln!(loader_file, "pub fn init_features() {{")?;

    for (feature, entry) in &map.0 {
        let trimmed_path = entry.path.trim();

        if let Some(call) = &entry.call {
            writeln!(loader_file, "    #[cfg(feature = \"{0}\")]", feature)?;
            writeln!(loader_file, "    {{ crate::{0}::{1}(); }}", trimmed_path, call)?;
        } else {
            writeln!(
                loader_file,
                "    // crate::{} - no init() call",
                trimmed_path
            )?;
        }

        auto_generate_stub(trimmed_path)?;
    }

    writeln!(loader_file, "}}")?;
    println!("[+] Regenerated feature_loader.rs with {} feature(s)", map.0.len());
    Ok(())
}

fn auto_generate_stub(path: &str) -> Result<()> {
    let file_path = Path::new("src").join(path.replace("::", "/" + "rs"));

    if file_path.exists() {
        println!("[+] Skipping, stub, file already exists: {}", file_path.display());
        return Ok(()); // Don't overwrite existing files
    }

    if let Some(parent) = file_path.parent() {
        fs::create_dir_all(parent)?;
    }

    let mut file = File::create(file_path)?;
    writeln!(file, "// AUTO-GENERATED MODULE STUB")?;
    writeln!(file, "pub fn init() {{")?;
    writeln!(file, "    println!(\"{}::init() called\");", path)?;
    writeln!(file, "}}")?;

    println!("[+] Created stub: {}", full_path);
    Ok(())
}
